# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.12.0.schema.json

PackageIdentifier: HighNovation.ODD-IT
PackageVersion: 2026.10.07.0917
DefaultLocale: fr-FR
ManifestType: version
ManifestVersion: 1.12.0
