# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: HighNovation.ODD-IT
PackageVersion: 2026.10.07.0917
InstallerLocale: fr-FR
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.18362.0
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /SILENT /SUPPRESSMSGBOXES /NORESTART
ExpectedReturnCodes:
- InstallerReturnCode: 7
  ReturnResponse: packageInUse
UpgradeBehavior: install
ProductCode: '{060F2AC0-CB70-45BB-AC4B-356157239542}_is1'
Installers:
- Architecture: x64
  InstallerUrl: https://high-novation.com/media/products/releases/odd-it/2026.10.07.0917/High-novation_ODD-IT-2026.10.07.0917.exe
  InstallerSha256: 4233278D3151F9A79A4484CB6722363269772D592BFBF7E8CD914CE3A927F1B7
- Architecture: x86
  InstallerUrl: https://high-novation.com/media/products/releases/odd-it/2026.10.07.0917/High-novation_ODD-IT-2026.10.07.0917.exe
  InstallerSha256: 4233278D3151F9A79A4484CB6722363269772D592BFBF7E8CD914CE3A927F1B7
ManifestType: installer
ManifestVersion: 1.12.0
