# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: HighNovation.SuperDSN
PackageVersion: 2026.10.07.0923
InstallerLocale: fr-FR
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: inno
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART
  SilentWithProgress: /SILENT /SUPPRESSMSGBOXES /NORESTART
ExpectedReturnCodes:
- InstallerReturnCode: 7
  ReturnResponse: packageInUse
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://high-novation.com/media/products/releases/superdsn/2026.10.07.0923/High-novation_SuperDSN-2026.10.07.0923.exe
  InstallerSha256: 1A97CB89CD6E7AAA519F7D2FF62FE218D39DD11B7C6D68B4B194FCB80EBE706F
  ProductCode: '{7F23E3B1-2D2B-4D55-9C64-2769213F0C13}_is1'
ManifestType: installer
ManifestVersion: 1.12.0
